### ISSUE TITLE
Error when use directly with jsreport-core

### ISSUE THREAD

**Issue by sdnetwork** [jsreport/jsreport-xlsx#13]
is there way to use only with jsreport-core like this (as phantom-pdf recipe hello exemple) : 

    jsreport.render({
                template: {
                    content: fs.readFileSync('./mytemplate.txt'),
                    engine: 'jsrender',
                    recipe: 'xlsx'
              }.then(function(respd) {
     }).catch(function(e) {})

mytemplate.txt

    {{#xlsxAdd "xl/worksheets/sheet1.xml" "worksheet.sheetData[0].row"}}
    {{/xlsxAdd}}
    {{{xlsxPrint}}}

but i get two errors : 

1) Error during rendering report: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
2) html.replace is not a function

to solve 1, i need to modify static/helpers.js to 'use strict'
i can't solve 2

any idea ?

**Comment by pofider** [comment]
It seems to work for me. Can you try it like this?

```js
var jsreport = require('jsreport-core')()
var fs = require('fs')

jsreport.use(require('jsreport-handlebars')())
jsreport.use(require('jsreport-templates')())
jsreport.use(require('jsreport-xlsx')())

jsreport.init().then(function () {
  return jsreport.render({
    template: {
      content: fs.readFileSync('template.handlebars').toString(),
      engine: 'handlebars',
      recipe: 'xlsx'
    }
  }).then(function (res) {
    res.stream.pipe(fs.createWriteStream('out.xlsx'))
  })
}).catch(function (e) {
  console.log(e)
})
```

**Comment by sdnetwork** [comment]
I begin to understand these problems :

for the first problem (Block-scoped declarations (let, const, function, class) not yet supported outside strict mode)

is due to node version : in 4.6.2 i have the error, with 6.9.1 the problem disapears !
i don't know if it's a known issue ?


for the second problem, it seems to be due to an error in my template i had an extra \n at the end.

**Comment by pofider** [comment]
>is due to node version : in 4.6.2 i have the error, with 6.9.1 the problem disapears !
i don't know if it's a known issue ?

Ah, this is not intentional, I'll fix that https://github.com/jsreport/jsreport-xlsx/issues/14


> for the second problem, it seems to be due to an error in my template i had an extra \n at the end.
Hm. It seems to work for me even with line ending. Can you try to break it here?

https://playground.jsreport.net/studio/workspace/r1vaurbw/42

**Comment by pofider** [comment]
The node 4 is now supported in [1.1.4](https://github.com/jsreport/jsreport-xlsx/releases/tag/1.1.4)

**Comment by sdnetwork** [comment]
> for the second problem, it seems to be due to an error in my template i had an extra \n at the end.
> Hm. It seems to work for me even with line ending. Can you try to break it here?
> https://playground.jsreport.net/studio/workspace/r1vaurbw/42

it seems to have an other difference with node 4.6.1 and 6.9.1 (and effectively is not due to \n)

with this template : 

    {{#xlsxAdd "xl/worksheets/sheet1.xml" "worksheet.sheetData[0].row"}}
    <row>
        <c t="inlineStr"><is><t>{{this}}</t></is></c>
    </row>
    {{/xlsxAdd}}
    {{{xlsxPrint}}}

it works on 6.9.1 but with 4.6.1 i have this error : 

    TypeError: Cannot read property 'parseString' of null
       at xml2json (evalmachine.<anonymous>:363:11)
       at xml2jsonUnwrap (evalmachine.<anonymous>:356:18)
       at Object.add (evalmachine.<anonymous>:169:23)
       at Object.<anonymous> (evalmachine.<anonymous>:397:17)
       at Object.eval (eval at createFunctionContext 

and with this template it works on both : 

      {{#each numbers}}
      {{#xlsxAdd "xl/worksheets/sheet1.xml" "worksheet.sheetData[0].row"}}
       <row>
         <c t="inlineStr"><is><t>{{this}}</t></is></c>
       </row>
       {{/xlsxAdd}}
       {{/each}}

       {{{xlsxPrint}}}

**Comment by pofider** [comment]
Hm. I cannot replicate it on node 4.6.1 on windows.

Based on the stack trace, it looks that the helpers are not able to require `xml2js` module for some reason, but I don't get what could be wrong.

**Comment by sdnetwork** [comment]
> Hm. I cannot replicate it on node 4.6.1 on windows.

Effectively, i'm on osx sierra, how i can help you to find the problem ?
i have diffulty to understand why the seond template works if a module (xml2js) couldn't be loaded ?

**Comment by pofider** [comment]
I don't get it as well, but the stack trace says the truth:)

I take a look at it tomorrow.

**Comment by sdnetwork** [comment]
Maybe an explanation :

If i add a xml2js dependency to my project it works !

After debug static/helpers.js, the safeRequire on xml2js fails because it seems to be not allowed when it is loaded from jsreport-xlsx/node_modules/xml2js but it is when is loaded from project/node_modules/xml2js

I have seen in  jsreport-xslx/lib/index.js that :

      if (reporter.options.tasks.allowedModules !== '*') {
         reporter.options.tasks.allowedModules.push('path');
         reporter.options.tasks.allowedModules.push('lodash');
         reporter.options.tasks.allowedModules.push(_path2.default.join(__dirname, '../node_modules/lodash'));
         reporter.options.tasks.allowedModules.push('xml2js');
         reporter.options.tasks.allowedModules.push(_path2.default.join(__dirname, '../lib/fsproxy.js'));
       }

i have add this line to this block, it works fine without need to have xml2js dependency to my project

         reporter.options.tasks.allowedModules.push(_path2.default.join(__dirname, '../node_modules/xml2js'));

**Comment by pofider** [comment]
Yes that was missing. Thank you for this brilliant investigation.

I've release 1.1.5 with the fix and I guess we can close this now.
