### ISSUE TITLE
Problem on xlsx template import when have "<" or ">" character

### ISSUE THREAD

**Issue by sdnetwork** [jsreport/jsreport-xlsx#15]
It seems there is a convertion problem during the import of xlsx template if there is < or > character in the template (i attach an example).

i can't reproduce the problem with the playground (1.0.6), but with the last version i can.

in fact excel need to convert < or > inside string by & lt; or & gt;, but after import into jsreport is converted on < or >

For example :

i put in a column text into excel :
"<2" 

if i open the xlsx i found 
"& lt;2" into sharedString.xml

but after import i found
"<2" into the converted content.txt file

the problem seems appear between 1.0.14 and 1.0.16 (jsreport-xlsx version)
[Classeur1.xlsx](https://github.com/jsreport/jsreport-xlsx/files/673846/Classeur1.xlsx)

**Comment by pofider** [comment]
Thank you for the submitted bug. I see the problem. I'm analyzing the solution now.

**Comment by pofider** [comment]
I believe this is now fixed in 1.1.6. Please reopen if it doesn't work for you with the latest.

**Comment by sdnetwork** [comment]
Thanks it works, but not in all part of excel archive for exemple in pivot it doesn't work (i attach an example)
[pivot.xlsx](https://github.com/jsreport/jsreport-xlsx/files/680669/pivot.xlsx)

**Comment by pofider** [comment]
Thank you for your feedback.
I see... I've forgotten to add escaping also to the attributes.

This is now hot fixed in 1.1.7

**Comment by sdnetwork** [comment]
it works thanks
