### ISSUE TITLE
Cannot able to edit sheet2  from my xlsx template

### ISSUE THREAD

**Issue by himanshusaini-91** [jsreport/jsreport-xlsx#23]
i upload my xlsx template through online playground  which have two worksheet example : sheet1 and sheet2 
i can edit sheet1 perfectly but i cannot able to edit sheet2 
i am using handle bars and xlsx in properties
i am using like this 
{{#xlsxAdd "xl/worksheets/sheet2.xml" "worksheet.sheetData[0].row"}}
    <row>
        <c  t="inlineStr"><is><t>asdfasdf</t></is></c>
        <c  t ="inlineStr"><is><t>sdfsadfasdf</t></is></c>
        <c  t ="inlineStr"><is><t>sdafsadfasdf</t></is></c>
        <c  t ="inlineStr"><is><t>sdfasdf</t></is></c>
        <c  t ="inlineStr"><is><t>sdafsadf</t></is></c>
        <c  t ="inlineStr"><is><t>asdfasdfasf</t></is></c>
    </row>
{{/xlsxAdd}}
but it gives me this error
  We're sorry, we couldn't open your workbook. It's possibly corrupt or using a file format that's not   supported.
if i use replace helper it will remove my predefined template and create new sheet 

can you please help me..

**Comment by pofider** [comment]
Try something like here, just change the sheet number

https://playground.jsreport.net/studio/workspace/r1vaurbw/3

Please link the playground sample with your issue if this didn't help.
