### ISSUE TITLE
Can't populate Cell with string containing '<='

### ISSUE THREAD

**Issue by joshplaetzler** [jsreport/jsreport-xlsx#28]
I'm trying to populate a cell with this string 'X<=1 in' using a helper that gets the string from an object. I'm able to get '<' to show up without changing anything but '=' comes through as '&#x3D;'  If I use `return new Handlebars.SafeString(string)` I can get it to return '=' but gives me an unencoded error for '<'.  Is there anyway to get the string to show both?  Also I tried using three brackets instead of two and that also did not work: {{{ }}}.

Example
cell:
`<c t="inlineStr"><is><t>{{getstring  type}}</t></is></c>`

Helper and Object:
```
function getString(type){
    return obj[type]
}

var obj = { "type1" : "X<=1 in", "type2": "X<= 2 in", "type3":  "X>= 3 in"}
```

**Comment by pofider** [comment]
Handlebars for some security reasons escapes `=` even that it is valid xml character. I didn't expect this.

I've released fix for `=` escaping now in `1.4.1`. Please install it using `npm install jsreport-xlsx` and let me know if it works for you now.

**Comment by joshplaetzler** [comment]
That did the Trick.  Thanks!

**Comment by pofider** [comment]
Great. Thank you for the confirmation.
