### ISSUE TITLE
Please extend #15 to include &apos; → ' (apostrophe, U+0027)

### ISSUE THREAD

**Issue by rashmim00** [jsreport/jsreport-xlsx#29]
Please extend #15 to include &apos; → ' (apostrophe, U+0027).

Jsreport generated data shows JOHN&#x27;S PET PRODUCTS.

**Comment by bjrmatos** [comment]
i can confirm the bug [here](https://playground.jsreport.net/studio/workspace/HJFy01TVG/6) (also locally OSX), we will provide a fix. thanks for the report.

**Comment by pofider** [comment]
Fixed in `1.4.2`. Thank you both.
