### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by ayozebarrera** [jsreport/jsreport-xlsx#33]
Hi, good job btw!

I have the following report

```handlebars
{{#xlsxAdd "xl/worksheets/sheet1.xml" "worksheet.sheetData[0].row"}}
  <row>
    <c t="inlineStr"><is><t>I should have no style</t></is></c>
  </row>
{{/xlsxAdd}}

{{#xlsxAdd "xl/worksheets/sheet1.xml" "worksheet.sheetData[0].row"}}
  <row>
    <c t="inlineStr"><is><t>I should be red</t></is></c>
  </row>
{{/xlsxAdd}}

{{{xlsxPrint}}}
```

How I suppose to apply style on a cell? (like text color or font weight!)

Thank you!

**Comment by pofider** [comment]
Thanks... You have two options. 

1. Prepare the style in the excel and then use it. There are several examples here
https://jsreport.net/learn/xlsx

2. Define your own styleSheet openxml manually and use it. This can be found in this demo.
https://playground.jsreport.net/studio/workspace/SyupOZ2Dz/5

Hope this helps

**Comment by ayozebarrera** [comment]
It helps, thanks for the reply.

Anyway, following the example, I couldn't update text... so I used fill colors. Just one more question: How do you apply a color to a text ?

**Comment by pofider** [comment]
The way you can find out is the following.
Create new excel and put there "Hello text" with the color you like.
Save it as xlsx. 
Rename it to zip.
Extract it and find how it is actually done in the styleSheet  xml.

**Comment by ayozebarrera** [comment]
Oh, thanks for solving me all the next doubts 😆 

good job guys!
