### ISSUE TITLE
Add line break in Xlsx recipe 

### ISSUE THREAD

**Issue by julienMifsud** [jsreport/jsreport-xlsx#40]
Hello, 

I have been using your JSReport module in my company and it is quite awesome.

I have a problem though.
I’m trying to put a line break in a Excel document from a JavaScript object, so my JavaScript object looks like this :

```
{
                “foo”: “bar \n foo \n bar”
}
```

But when I convert my XML into a .xlsx document, my line break doesn’t appear in my document.
Any idea on how to do so ?

Thank you for your time.

**Comment by pofider** [comment]
This is all about studying how this is done in the xlsx/openxml source. I do it usually by replicating the problem in excel app and check what it's doing with the XML source.

This time the cell needs to have "Wrap text" enabled in order to print \n as line break.
You can do this by right click on the cell, Format Cells/Alignment/Wrap Text.
This creates a specific line in the styles.xml and references the style in your cell.
In the best case, you can just-style the cells in the excel app and reuse it to avoid a need to alter `styles.xml` dynamically.  See this example
https://playground.jsreport.net/w/anon/cKUBOO7c

**Comment by julienMifsud** [comment]
Thank you for your answer but I think it does not solve my problem...
I can't use your solution because I have dynamically generated data, that I get from an external API, so I can't define where my line break should be in my `styles.xml` file. If i apply the line break style for a cell, it will break the line everytime a word is entered in this line, but it is not what i want.

Isn't it possible to define, in the string displayed in the cell, some keyword like `\n` to break the line, like it's done in HTML?

Thank you again.

**Comment by pofider** [comment]
It seems you either have wrap text disabled for the cell and it looks like this

![image](https://user-images.githubusercontent.com/2041960/83722740-d7aee280-a63d-11ea-8b57-ef1b0f24735b.png)

or you have it enabled and it looks like this then

![image](https://user-images.githubusercontent.com/2041960/83722850-fb722880-a63d-11ea-971e-96e537941897.png)

Both times there is an explicit line break after the "word one"

**Comment by julienMifsud** [comment]
Hello,
I think I just came to understand where the problem was.
It is working for the line break, but I still have to execute the "Wrap text" action when I open my .xlsx file like in the first picture. 

![cap1](https://user-images.githubusercontent.com/55246918/84036888-26da7780-a99e-11ea-9114-961856d723da.PNG)

In the same picture, you can see that the column below "Commentaire" is not wrapped, even though in the column definition above, I can see that the text is wrapped.

But when I clic on the "Wrap text" button, as shown in the first picture, I get this result :

![cap2](https://user-images.githubusercontent.com/55246918/84036964-39ed4780-a99e-11ea-8c8b-ffcb68e35b7b.PNG)


Any chance that I can automatically do it by modifying the alignment tag ? 
Maybe it is something that you already answered in this issue, and I'm sorry if it is the case!

Thank you again for your time.

**Comment by pofider** [comment]
This is exactly what I was mentioning in my first comment. 
You need to either set the wrap text inside the excel and reuse the style or edit the `styles.xml` using the `xlsx` helpers.
Here is an example of how to prepare the style in the desktop excel and reuse it 
https://playground.jsreport.net/w/anon/GnHan~55

**Comment by julienMifsud** [comment]
I think that should do it, but I'm still that I have to do it manually and not programmatically.
Thank your for your time and your answers!
