### ISSUE TITLE
Long processing problem

### ISSUE THREAD

**Issue by DanBrk** [jsreport/jsreport-xlsx#41]
I am trying to generate excel file of about 15,000 rows and it takes a long time. According to the log file the duration is 16 seconds.

> 2020-06-28T16:38:09.487Z - info: Rendering request 16375 finished in 16261 ms
> 2020-06-28T16:38:19.325Z - info: Starting rendering request 16376 (user: null)
> 2020-06-28T16:38:19.325Z - info: Rendering template { name: purple-list-to-excel-v3-rtl, recipe: xlsx, engine: handlebars, preview: false }

I am using my own template file with not xslx confiiguration.
Can you please explain the configuration parameters 'numberOfParsedAddIterations' and 'addBufferSize' ?
I there away to improve the performance ?

**Comment by pofider** [comment]
Closing as duplicate to https://forum.jsreport.net/topic/1633/long-duration-excel-generation/2
