### ISSUE TITLE
Method of include for `helpers.js` appears to conflict with native helpers

### ISSUE THREAD

**Issue by danielsharvey** [jsreport/jsreport-xlsx#5]
The method of including the XLSX helpers in `lib/index.js` appears to conflict with native helpers - appending a string and an object breaks the render.

```
return FS.readFileAsync(_path2.default.join(__dirname, '../', 'static', 'helpers.js'), 'utf8').then(function (content) {
        return req.template.helpers = content + '\n' + (req.template.helpers || '');
});
```

**Comment by pofider** [comment]
It should not, look here https://playground.jsreport.net/studio/workspace/r1vaurbw/12

Maybe you are setting helpers as object? Like this?

```js
{
  myHelper: function () {
  }
}
```

Note that helpers should be registered as global functions:
```js
function myHelper() {
}
```

**Comment by danielsharvey** [comment]
I'm following documentation here  [jsreport-core](https://github.com/jsreport/jsreport-core) as per section 'Native helpers'.

So yes, defining similar to your first example. Shouldn't that work? 

How do I register a global function as a helper in jsreport-core?

**Comment by pofider** [comment]
Ah, you are right. I'll need to fix it here. Give me a minute.

**Comment by danielsharvey** [comment]
Code makes sense. Thanks for the super-fast response. I'll try it out.
