### ISSUE TITLE
Unable to add rows to Excel table

### ISSUE THREAD

**Issue by zam6ak** [jsreport/jsreport-xlsx#8]
I am using Excel template that has a table with one dummy row.
The goal being to add real data to Excel table during report generation.

I followed the Chart example (https://playground.jsreport.net/studio/workspace/rJftqRaQ/10) which (as far as I can tell, since docs are not clear) removes the dummy row first and then adds real data.
The problem is that added rows are not part of the Excel table, and therefore cannot be sorted or filtered using column headings....
If you run the example, notice **that only first row is part of the table** (because it is defined that way in Excel template)

In Order to accomplish this 2 attributes need to be modified in the Excel XML template during rendering.

* file: "xl/tables/table1.xml"
* element: "table", attribute: "ref" - needs to capture the range of all rows (from A1 to ZZ9999) where ZZ9999 is the last column:row of the table
* element: "autoFilter", attribute "ref" - same as above

sample
```
<table xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" id="1" name="Table1" displayName="Table1" ref="A1:R3800" totalsRowShown="0" headerRowDxfId="19" dataDxfId="18">
  <autoFilter ref="A1:R3800"/>
  <tableColumns count="18">
    <tableColumn id="1" name="Id" dataDxfId="17"/>
    ....
    ...
    .
</table>
```

In the above example, ref had to change from "A1:R2" to "A1:R3801" because the real data has 18 columns (which ends up being column "R" in Excel) and 3800 rows (which is in Excel in rows 3801 because of extra header row)

So, can this be accomplished and how?
I assume that this requires "knowing" the total number of rows in advance to template manipulation can take place.....

**Comment by pofider** [comment]
Sorry for the dumb question, but do you really need excel table? Cannot you stick with standard excel range which supports filtering as well? 

Take a look at simple demo and download the report output. You should see that filtering works for new dynamic rows. 
https://playground.jsreport.net/studio/workspace/Sy2ETVbh/4

In case you need more advanced excel features like pivot table, you can set up the datasource to be dynamic directly in the excel template. This is described in this tutorial: http://jsreport.net/learn/dynamic-excel-pivot-table

**Comment by zam6ak** [comment]
Not a dumb question at all!
The system we are trying to replace (based on Apache FOP) has customer reports that contain Excel tables. Besides sorting, filtering, etc, etc. tables have other features being used (e.g. summary rows).
So, yes tables, in our case, are needed.

**Comment by pofider** [comment]
Ok. I've prepared example with dynamic table here:
https://playground.jsreport.net/studio/workspace/Hy_V2BSh/4

**Comment by pofider** [comment]
I've add the link also to docs. 

Hope the example is clear - I basically just update the attributes in table you mentioned using $xlsxMerge helper.

Closing this now, feel free to comment or reopen if you have something to add.

**Comment by zam6ak** [comment]
Apologies for late reply, I just tried to apply this to my data set....
I still don't get how is merge helping here?
And what about column and row references? How would you get those dynamically?
xslxMerge seems to be lacking in documentation so I dont knwo what autoFilter is and how does this work....

Could you possibly create an example that is a bit more realistic...
Like with 10-20 rows of data in data file being added to Excel table

**Comment by zam6ak** [comment]
After playing around with the merge I got the table to populate.
However, how can I dynamically reference # of rows to reference attribute (from data fro example)?
This works now only if you know the number of rows (and columns) in advance...

**Comment by pofider** [comment]
> However, how can I dynamically reference # of rows to reference attribute (from data fro example)?

I don't understand what you mean, could you please describe it?

**Comment by zam6ak** [comment]
The table references a range `A1:R3800` which is starting_column _and_row:ending_column_and_row.
Starting column and row could be fixed (A1) but ending column and row depends on number of columns and rows in your data...
Even ending column could be static, but number of rows would change...
If the range is not exact the table will not encompass all the rows.
Try adding two more rows in your example without changing the references and see what happens...

I can send rowCount as part of the data - can that be used somehow to dynamically adjust the range?

**Comment by bamdad-b** [comment]
I want to achieve the same thing. Dynamic rows and columns in a table. Any update?
